runtime: nodejs18
entrypoint: node server/express.js
env_variables:
  PORT: 3000
  FRONTEND_PORT: 8080
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html