apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing123
  labels:
    app: labeltesting
spec:
  replicas: 5
  selector:
    matchLabels:
      app: labeltesting
  template:
    metadata:
      labels:
        app: labeltesting
    spec:
      containers:
        - name: labeltesting
          image: margaritabizhan/getting-started
          ports:
            - containerPort: 3000
