apiVersion: apps/v1
kind: Deployment
metadata:
  name: cristina111
  labels:
    app: rita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rita
  template:
    metadata:
      labels:
        app: rita
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081