apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing123
  labels:
    app: label-testing
spec:
  replicas: 5
  selector:
    matchLabels:
      app: label-testing
  template:
    metadata:
      labels:
        app: label-testing
    spec:
      containers:
        - name: label-testing
          image: margaritabizhan/getting-started
          ports:
            - containerPort: 3000
