apiVersion: apps/v1
kind: Deployment
metadata:
  name: boba
  labels:
    app: boba
spec:
  selector:
    matchLabels:
      app: boba
  template:
    metadata:
      labels:
        app: boba
    spec:
      containers:
        - ports:
            - containerPort: 8080
          name: boba
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
  replicas: 3
