apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test-label
spec:
  selector:
    matchLabels:
      app: test-label
  template:
    metadata:
      labels:
        app: test-label
    spec:
      containers:
        - image: margaritabizhan/getting-started
          ports:
            - containerPort: 3000
          name: test-label
  replicas: 2
