apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - ports:
            - containerPort: 
          image: margaritabizhan/getting-started
          name: hello-node
  replicas: 3
