apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
  labels:
    app: gcloud-deployment
spec:
  selector:
    matchLabels:
      app: gcloud-deployment
  template:
    metadata:
      labels:
        app: gcloud-deployment
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: gcloud-deployment
          image: tbensalem/getting-started
  replicas: 3
