apiVersion: apps/v1
kind: Deployment
metadata:
  name: yay
  labels:
    app: yayyyyyy
spec:
  selector:
    matchLabels:
      app: yayyyyyy
  template:
    metadata:
      labels:
        app: yayyyyyy
    spec:
      containers:
        - ports:
            - containerPort: 1001
          name: yayyyyyy
          image: tbensalem/getting-started
  replicas: 5
