apiVersion: apps/v1
kind: Deployment
metadata:
  name: test123
  labels:
    app: my-label
spec:
  selector:
    matchLabels:
      app: my-label
  template:
    metadata:
      labels:
        app: my-label
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: my-label
          image: margaritabizhan/getting-started
  replicas: 2
