apiVersion: apps/v1
kind: Deployment
metadata:
  name: sadsad
  labels:
    app: asdsad
spec:
  selector:
    matchLabels:
      app: asdsad
  template:
    metadata:
      labels:
        app: asdsad
    spec:
      containers:
        - ports:
            - containerPort: 8080
          name: asdsad
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
  replicas: 1
