apiVersion: apps/v1
kind: Deployment
metadata:
  name: hihi
  labels:
    app: hi
spec:
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: hi
          image: margaritabizhan/getting-started
  replicas: 2
