apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: app
          image: margaritabizhan/getting-started
  replicas: 3