apiVersion: apps/v1
kind: Deployment
metadata:
  name: ''
  labels:
    app: test-label
spec:
  selector:
    matchLabels:
      app: test-label
  template:
    metadata:
      labels:
        app: test-label
    spec:
      containers:
        - ports:
            - containerPort: 8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          name: test-label
  replicas: 1
