apiVersion: apps/v1
kind: Deployment
metadata:
  name: hichem
  labels:
    app: zammel
spec:
  selector:
    matchLabels:
      app: zammel
  template:
    metadata:
      labels:
        app: zammel
    spec:
      containers:
        - ports:
            - containerPort: 8080
          name: zammel
          image: tbensalem/getting-started
  replicas: 1
