apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt
  labels:
    app: lll
spec:
  selector:
    matchLabels:
      app: lll
  template:
    metadata:
      labels:
        app: lll
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: lll
          image: margaritabizhan/getting-started
  replicas: 3
