apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarik
  labels:
    app: ff
spec:
  selector:
    matchLabels:
      app: ff
  template:
    metadata:
      labels:
        app: ff
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: ff
          image: tbensalem/getting-started
  replicas: 2
