apiVersion: apps/v1
kind: Deployment
metadata:
  name: ''
  labels:
    app: test-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-label
  template:
    metadata:
      labels:
        app: test-label
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081