apiVersion: apps/v1
kind: Deployment
metadata:
  name: rita
  labels:
    app: hi
spec:
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: hi
          image: tbensalem/getting-started
  replicas: 2
