apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-click
  labels:
    app: final-test-of-doom
spec:
  selector:
    matchLabels:
      app: final-test-of-doom
  template:
    metadata:
      labels:
        app: final-test-of-doom
    spec:
      containers:
        - ports:
            - containerPort: 3000
          name: final-test-of-doom
          image: tbensalem/getting-started
  replicas: 3
