apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-app
  labels:
    app: rita
spec:
  selector:
    matchLabels:
      app: rita
  template:
    metadata:
      labels:
        app: rita
    spec:
      containers:
        - ports:
            - containerPort: 3000
          image: margaritabizhan/getting-started
          name: rita
  replicas: 5
