apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: other-app
  labels:
    app: rita
spec:
  selector:
    matchLabels:
      app: rita
  template:
    metadata:
      labels:
        app: rita
=======
  name:
  name: a-a
  name: my-test-app
  labels:
    app:
    app: a-a
    app: gcloud-deployment
spec:
  selector:
    matchLabels:
      app:
      app: a-a
      app: gcloud-deployment
  template:
    metadata:
      labels:
        app:
        app: a-a
        app: gcloud-deployment
>>>>>>> dev
    spec:
      containers:
        - ports:
            - containerPort: 3000
<<<<<<< HEAD
          image: margaritabizhan/getting-started
          name: rita
  replicas: 5
=======
          name:
          image:
  replicas: 3
            - containerPort: 8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          name: a-a
  replicas: 2
            - containerPort: 3000
          name: gcloud-deployment
          image: tbensalem/getting-started
  replicas: 3
>>>>>>> dev
