apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-a
  labels:
    app: a-a
spec:
  selector:
    matchLabels:
      app: a-a
  template:
    metadata:
      labels:
        app: a-a
    spec:
      containers:
        - ports:
            - containerPort: 8080
          name: a-a
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
  replicas: 3
