apiVersion: apps/v1
kind: Deployment
metadata:
  name: ri
  labels:
    app: rita
spec:
  selector:
    matchLabels:
      app: rita
  template:
    metadata:
      labels:
        app: rita
    spec:
      containers:
        - ports:
            - containerPort: 2998
          name: rita
          image: margaritabizhan/getting-started
  replicas: 3
