apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomname1
  labels:
    app: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: margaritabizhan/getting-started
          ports:
            - containerPort: 3000
